v5.0 port initial commit

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,3 +1,4 @@
+
 #!/bin/sh -e
 # Note: the '-e' flag will make the script stop immediately upon error with 
 # the error reflected in the environment.  This lets one issue commands like
@@ -7,6 +8,13 @@ F=$1
 O=$2
 OPT=0
 FLAGS="-g"
+EXTRA_CFLAGS=""
+MAIN_SRC="$F.c"
+
+if [ "$F" = "jjbitxd" ]; then
+    EXTRA_CFLAGS="-DJJ_HEADLESS_DAEMON=1"
+    MAIN_SRC="sbitx.c"
+fi
 [ -z "$F" ] && {
    echo "usage:   $0 program [o|g|u]"
    echo "example: $0 sbitx"
@@ -61,21 +69,59 @@ else
   VERSION=`grep VER src/sdr_ui.h | awk 'FNR==1{print $4}' | sed -e 's/"//g'`
   echo "compiling $F version $VERSION in $WORKING_DIRECTORY"
 fi
-gcc $FLAGS -o $F \
-	 src/vfo.c src/si570.c src/sbitx_sound.c src/fft_filter.c  src/sbitx_gtk.c src/sbitx_utils.c \
-    src/i2cbb.c src/si5351v2.c src/ini.c src/hamlib.c src/queue.c src/modems.c src/logbook.c \
-		src/modem_cw.c src/settings_ui.c src/oled.c src/hist_disp.c src/ntputil.c \
-		src/telnet.c src/macros.c src/modem_ft8.c src/remote.c src/mongoose.c src/webserver.c src/$F.c  \
-		src/ft8_lib/libft8.a  \
-	-lwiringPi -lasound -lm -lfftw3 -lfftw3f -pthread -lncurses -lsqlite3 -lnsl -lrt \
-	`pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`
+# Define Mongoose SSL flags - ensure OpenSSL is properly enabled
+MONGOOSE_FLAGS="-DMG_ENABLE_OPENSSL=1 -DMG_ENABLE_MBEDTLS=0 -DMG_ENABLE_LINES=1 -DMG_TLS=MG_TLS_OPENSSL -DMG_ENABLE_SSI=0 -DMG_ENABLE_IPV6=0"
 
+gcc $FLAGS $EXTRA_CFLAGS $MONGOOSE_FLAGS -o $F \
+	 src/vfo.c src/si570.c src/sbitx_sound.c src/fft_filter.c src/sbitx_gtk.c src/sbitx_utils.c \
+    src/i2cbb.c src/si5351v2.c src/ini.c src/hamlib.c src/queue.c src/modems.c src/logbook.c \
+		src/modem_cw.c src/settings_ui.c src/hist_disp.c src/ntputil.c \
+		src/telnet.c src/macros.c src/modem_ft8.c src/remote.c src/mongoose.c src/para_eq.c src/webserver.c src/eq_ui.c src/$MAIN_SRC  \
+		src/ft8_lib/libft8.a  \
+	-lwiringPi -lasound -lm -lfftw3 -lfftw3f -pthread -lncurses -lsqlite3 -lnsl -lrt -lssl -lcrypto \
+	`pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`
+ 
 if [ $OPT -eq 1 ]; then
 	#Remove debugging stuff for a smaller binary
 	echo Stripping $F
 	strip $F
 fi
-echo "Brought to you by the sBitx 64 bit project team - W9JES, W2JON, N1QM, OZ7BX, W4WHL, and KF7YDU" 
+
+# Open the user_settings.ini file, search for #60m=, and add it if missing
+if [ -f "$HOME/sbitx/data/user_settings.ini" ]; then
+    echo "Checking user_settings.ini for 60 meters"
+    if ! grep -q "^#60m=" "$HOME/sbitx/data/user_settings.ini"; then
+        echo "Adding 60 meter band to user_settings.ini"
+        sed -i '/#40m=/a\#60m=' "$HOME/sbitx/data/user_settings.ini"
+    else
+        echo "60 meter band already exists in user_settings.ini"
+    fi
+else
+    echo "user_settings.ini not found"
+fi
+
+# Update hw_settings.ini to add 60m band configuration
+if [ -f "$HOME/sbitx/data/hw_settings.ini" ]; then
+    echo "Checking hw_settings.ini for 60m band"
+    if grep -q "f_start=5250000" "$HOME/sbitx/data/hw_settings.ini"; then
+        echo "60m band already exists in hw_settings.ini"
+    else
+        echo "Adding 60m band to hw_settings.ini"
+        awk '{
+          print $0
+        } /f_start=3500000/ {
+          found=1
+        } found && /scale=/ {
+          print ""
+          print "[tx_band]\nf_start=5250000\nf_stop=5450000\nscale=0.0033"
+          found=0
+        }' $HOME/sbitx/data/hw_settings.ini > temp.ini && mv temp.ini $HOME/sbitx/data/hw_settings.ini
+    fi
+else
+    echo "hw_settings.ini not found"
+fi
+
+echo "Brought to you by the sBitx 64 bit project team"
 echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
 # This addition is used to provide the application the capability to adjust the local system time -W2JON
 # It should probably always run last at it'll fail if the file system doesn't support it - N1QM
